label introduction:
    "Nobody really noticed when Death died."
    "It was an end to a great universal truth, yes."
    extend " It was the end to the great question that dogged in our footsteps, sooner or later - when comes our time?"
    extend " It was, perhaps, even the end to that struggle we know as the human condition."
    "Immortality, as they say, is a hell of a drug."
    "But when that day came, when Death looked itself in the mirror and decided he was long overdue, nobody cared."

    "Maybe there was a little breeze, a little vibrant wind fluttering around our heels, new life breathed into our movements."
    extend " Maybe the sky lightened a bit."
    extend " Maybe we had a few miracles in our hospitals."
    "Who knows."
    "Death was the disquieting neighbor that we never liked. He moved out without much fanfare."
    "A few weeks down the line, though, the world started to feel his absence."
    extend " The terminally sick terminated their sickness."
    extend " War became drawn-out; muggings became shocking."
    "Life had become a fact"
    extend "- death, a mistake rectified."
    "There was no danger anymore of alcohol poisoning - so the celebrations became a bit more drunken."
    "To nearly all, life glittered with a sheen unseen, perhaps what it truly was: well and perfect, when the grime of certain death was scrubbed away."
    "So for weeks, we held Death a mighty funeral, banquets, games. Perhaps somebody mourned him, but the rest of us were merely freedmen."
    extend " It was the best of times,"
    " it was the worst of times."
    extend " The churches faced revolt, collapse - their afterlife was lost to them forever." 
    "There were a few gruesome attempts at forcibly crossing that forbidden barrier between life and death, trying to claim their lives’ investment in holier things. But they were small bumps in the collective good feeling."
    "Still, perhaps it was then that we began to realize this immortality business wasn’t all roses..."
    "They watch you among the maze of planks that’s Main Street."
    "Grime-filled eyes sifting through the forest of dirty men and women to stare, a horde of bodies lined up alongside the weed-choked road."
    "Since the end of Death, maintaining the City had become difficult."
    "Grass would not be trampled - the fresh planks of new buildings would sprout branches and leaves every spring - the rats that gnawed at the fresh growth too multiplied without end."
    "They’d taken to dumping all the rats they could find into a fire-pit: even if fire couldn’t kill them, it’d burn away at their flesh."
    "Sure, the meat would regenerate as soon as you turned away (one of the many gifts that deathlessness had given to all creatures, human and rat alike), but that simply meant more fuel for the flames. It was a stasis of sorts."
    "You shake your head to clear the constant hissing screams of rat-pits out of your head, and smile for the crowd. You notice that the youngest looks no less than 14. "
    "When the old people stopped dying, they banned childbirths. It’s a sort of irony - when death died, so did all future generations of the human race."
    "When death died, so followed many things. You sweep your eyes across the shantytown that’s the outer edge of the City. This is all that is left of humanity."
    "Immortality for all, shockingly, meant immortality for all - the armored titan"
    "-ic dragons of the west, originally kept in check by their food supply, multiplied once they refused to die of starvation."
    "When their food supply also failed to die of starvation...well..."
    "There was a reason all remaining humanity was crammed inside a single walled city."
    extend "The reason might have been \"massive amounts of airbourne dragon-tanks.\""
    "Dragons and men had always been at war, having never managed to get past the racism inherent with the ability or lack thereof of breathing fire. But I digress."
    "We were discussing the losers that had nothing better to do with their lives except watch a boring bunch like you walk on the street."
    "They’re here to see the newest dispatch from the Excursion Council: you, Tomo-chan, and Tomo-kun."
    extend "The fifth such team off on a grand adventure to kick ass and unkill Death."
    "It just so happens that you’re all out of ass."
    "You grin at the sullen-looking populace. Their eyes speak of despair, hopelessness - they don’t believe in their salvation, their freedom from the oppression that is deathlessness."
    "They don’t think you can do it."
    "Must not make use of their brain cells on a regular basis. This is why you’re part of the elite and they aren’t. Sucks."
    "The gate looms open ahead of you - the exit from the last bastion of humanity, the walled city of Honno. From here on out, it’s all overgrown wilderness that just won’t die no matter how many times you kill it."
    "Just the way we like it."


    return
